[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    fast: Fast running unit tests without heavy framework overhead
    tensorflow: Unit tests requiring TensorFlow / Keras framework
